### ISSUE TITLE
IOException in Randomize()

### ISSUE THREAD

**Issue by authorblues** [jciii91/pokemon-stadium-randomizer#1]
Seems to be throwing an Exception silently for me. Not sure what specifically it was taking issue with. Tried running the jar from the command line so I could see a stacktrace, but no stacktrace was emitted.

One concern is that it will accept almost any file as input, it seems, and will put out a PKseed.z64 when it fails for any reason, so it wasn't until I looked further that I realized that it wasn't working. The rom it produced was a correctly working Pokemon Stadium rom that had no changes from the original.

**Comment by jciii91** [comment]
I'll add a check for the .z64, should be a quick fix there. Also going to add in feedback so that you'll know if there was a failure or a success without hunting for the answer.

As for the IOException, something broke when the actual randomizing was happening. The function that does the actual file changes starts by making that unedited copy, so I at least know it made it in there. I'll make changes to the error reporting, try and get more descriptive/helpful messages to trace where this is happening.

Would you have time to get on a Discord call to look at this? It'd be helpful to see what leads up to the failure and also get a look at the file.

**Comment by jciii91** [comment]
Did a quick revision this morning, should give you a better idea of why an error is happening. Latest release has the changes.

**Comment by jciii91** [comment]
Going to close this issue for now. I've done some new releases that I think address the original post.
